import { useEffect, useState } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { api, DocPage, DocPageMeta } from "../api"
import { Mermaid } from "../Mermaid"

export const PERSONAS = [
  ["onboarding", "Developer",
   "Architecture, entry points, and how the pieces fit - for someone joining this codebase."],
  ["sre", "SRE / On-call",
   "Where execution enters, what fails together, and the widest blast radii."],
  ["tester", "QA / Tester",
   "Regression risk, the surfaces worth exercising, and integration seams."],
] as const

export const PERSONA_LABELS: Record<string, string> =
  Object.fromEntries(PERSONAS.map(([v, label]) => [v, label]))

// persona + generation state live in App so writing continues (and stays
// visible) while the user browses other spaces
export function Docs({ snap, persona, generating, onPersona, demo }: {
  snap: number
  persona: string
  generating: boolean
  onPersona: (p: string) => void
  demo?: boolean
}) {
  const [tree, setTree] = useState<DocPageMeta[] | null>(null)
  const [slug, setSlug] = useState<string | null>(null)
  const [page, setPage] = useState<DocPage | null>(null)
  const [error, setError] = useState("")

  useEffect(() => {
    setSlug(null)
    setPage(null)
    api.docsTree(snap, persona).then((t) => {
      setTree(t)
      if (t.length) setSlug(t[0].slug)
    }).catch((e) => setError(String(e)))
  }, [snap, persona, generating])

  useEffect(() => {
    if (slug === null) return
    api.docsPage(snap, persona, slug)
      .then((p) => { setPage(p); setError("") })
      .catch((e) => setError(String(e)))
  }, [snap, persona, slug])

  if (tree !== null && tree.length === 0) {
    return (
      <div className="view">
        {generating ? (
          <div className="hint">
            <p><span className="spinner" /> Writing{" "}
              <b>{PERSONA_LABELS[persona]}</b> documentation: reading the
              graph, drafting sections, verifying every citation. This takes
              a few minutes, and it keeps going if you browse elsewhere.</p>
          </div>
        ) : (
          <div className="persona-pick">
            <h2>Who is this documentation for?</h2>
            <p className="muted">Osprey CodeGraph writes each audience its own pages
              from the same code graph: diagrams compiled from real
              dependencies, every <code>file:line</code> citation verified
              against the snapshot before publishing.</p>
            <div className="persona-cards">
              {PERSONAS.map(([v, label, blurb]) => (
                <button key={v}
                        className={`persona-card ${v === persona ? "active" : ""}`}
                        onClick={() => onPersona(v)}>
                  <b>{label}</b>
                  <span className="muted">{blurb}</span>
                  <span className="persona-go">{demo ? "View →" : "Generate →"}</span>
                </button>
              ))}
            </div>
            {demo && (
              <p className="muted small">On this demo, documentation is
                generated by the operator. If a persona is empty for the repo
                you care about, request it via ＋ Add repo and we'll run it
                for you.</p>
            )}
            {error && <div className="error">{error}</div>}
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="view docs">
      <div className="docs-body">
        <nav className="docs-tree">
          <select value={persona} onChange={(e) => onPersona(e.target.value)}>
            {PERSONAS.map(([v, label]) =>
              <option key={v} value={v}>{label}</option>)}
          </select>
          {(tree ?? []).map((p) => (
            <button key={p.slug}
                    className={`docs-link ${p.slug === slug ? "active" : ""} ${p.parent_slug ? "child" : ""}`}
                    onClick={() => setSlug(p.slug)}>
              {p.title}
              {p.status !== "verified" && (
                <span className="muted" title="some citations could not be verified"> ◦</span>
              )}
            </button>
          ))}
        </nav>
        <article className="docs-content">
          {error && <div className="error">{error}</div>}
          {page && (
            <>
              <div className="docs-head">
                <h1>{page.title}</h1>
                {page.status === "verified"
                  ? <span className="pill verified">✓ citations verified</span>
                  : <span className="pill">draft</span>}
              </div>
              <div className="md">
                <ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml
                  components={{
                  code({ className, children, ...props }) {
                    const text = String(children ?? "")
                    if (className?.includes("language-mermaid")) {
                      return <Mermaid code={text} />
                    }
                    return <code className={className} {...props}>{children}</code>
                  },
                }}>
                  {page.content_md}
                </ReactMarkdown>
              </div>
              <p className="muted docs-foot">Describes commit{" "}
                <code>{page.commit.slice(0, 8)}</code> · diagrams compiled
                from the dependency graph · citations verified against the
                snapshot</p>
            </>
          )}
        </article>
      </div>
    </div>
  )
}
